# -*- coding: utf-8 -*-
"""fe_flowchart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSDejDHGPfNYCR7XgOVIFmzI8BsbE6JO
"""

from graphviz import Digraph
from IPython.display import Image

# Create a directed graph
#dot = Digraph(comment='Cyber Threat Insight - Feature Engineering Workflow', format='png')
dot = Digraph("Cyber Threat Insight - Feature Engineering Workflow", format="png")


# Feature Engineering Phases
dot.node('Start', 'Start')
dot.node('DataInj', 'Data Injection\n(Cholesky-Based Perturbation)', shape='box', style='filled', fillcolor='lightblue')
dot.node('Scaling', 'Feature Normalization & Scaling\n(Min-Max, Z-score)', shape='box', style='filled', fillcolor='lightgray')
dot.node('CorrHeat', 'Correlation Heatmap Analysis\n(Pearson/Spearman)', shape='box', style='filled', fillcolor='orange')
dot.node('FeatImp', 'Feature Importance\n(Random Forest)', shape='box', style='filled', fillcolor='gold')
dot.node('SHAP', 'Model Explainability\n(SHAP Values)', shape='box', style='filled', fillcolor='lightgreen')
dot.node('PCA', 'PCA & Variance Explained\n(Scree Plot)', shape='box', style='filled', fillcolor='plum')
dot.node('Augment', 'Data Augmentation\n(SMOTE, GAN)', shape='box', style='filled', fillcolor='lightpink')
dot.node('End', 'Feature Set Ready for Modeling', shape='ellipse', style='filled', fillcolor='lightyellow')

# Arrows to show workflow
dot.edge('Start', 'DataInj')
dot.edge('DataInj', 'Scaling')
dot.edge('Scaling', 'CorrHeat')
dot.edge('CorrHeat', 'FeatImp')
dot.edge('FeatImp', 'SHAP')
dot.edge('SHAP', 'PCA')
dot.edge('PCA', 'Augment')
dot.edge('Augment', 'End')

features_engineering_flowchart = dot.render("features_engineering_flowchart", format="png", cleanup=False)
display(Image(filename="features_engineering_flowchart.png"))
print("Flowchart generated successfully!")